### ISSUE TITLE
unversioned critcl packages

### ISSUE THREAD

**Issue by pooryorick** [andreas-kupries/critcl#60]
Critcl installs the packages "stubs", "util84", "critcl-platform", and "critcl-emap1" into directories that don't include any version information.  This leaves the door open for contention between installations of different versions of criticl.  Could these directories also be versioned?

**Comment by andreas-kupries** [comment]
I agree that these should be versioned.

**Comment by andreas-kupries** [comment]
Note __critcl-emap__ is apparently versioned (The __1__ in "critcl-emap1").

**Comment by andreas-kupries** [comment]
Addressed in commits 2747985ab771f56ec43b868f6116b8f99968f4ad
and b58917c27b41575b8974014c95edd5fd6d333a25.

With the exception of `critcl-emap`, which is versioned all the other directories were bundles of packages, not singles, and as such could not have a version number, as the packages inside would have multiple different ones.

The above-referenced 1st commit splits all the bundle directories into several, so that we always have one package per directory, allowing the installed directory to have the version of the contained package. The other commit updates the tests to the new location of files.
