### ISSUE TITLE
Better visibility for the interp argument to a cproc

### ISSUE THREAD

**Issue by dkfellows** [andreas-kupries/critcl#96]
Right now, the [docs for `critcl::cproc`](https://andreas-kupries.github.io/critcl/doc/files/critcl_pkg.html#7) say:

> Further note that the type of the first argument is allowed to be __Tcl_Interp*__. In that case the argument in question is not counted as an argument of the new Tcl command.

Alas, that's far too easy to miss! It should be changed to be more like the other argument types, perhaps more like this (as the first argument type in the list, before the __Tcl_Obj*__ type):

> __Tcl_Interp*__  
> If the _first_ argument is of this type, the function takes a hidden Tcl interpreter argument (often called __interp__ by convention). This will not be visible at the Tcl level, but will be visible in the C code. It is essential for working with the __object__, __object0__ and __ok__ return types when producing a Tcl error.

Those return types probably need to specifically call out the __Tcl_Interp*__ argument type as being useful/essential when returning something interpreted as `TCL_ERROR`.

**Comment by andreas-kupries** [comment]
@dkfellows Please check if PR #101 is what you envisioned.

Reading the formatted documentation, i.e. the files
- `embedded/www/files/critcl_pkg.html` and
- `embedded/man/files/critcl_pkg.n`

instead of or in conjunction with the patch, the changes are found around the markers
- `setting an error` (result types), and
- `special` (argument type).

**Comment by andreas-kupries** [comment]
Fix merged after addressing Donal's comment.
